/**
 * @file Main_PSP.cpp
 * @brief PSP entry point — boots the engine, runs the main loop, exits clean.
 *
 * Mirrors the desktop Standalone/Source/Main.cpp boot sequence (Oct* hooks
 * → GameMain) but uses PSPSDK entry conventions:
 *
 *   - PSP_MODULE_INFO + PSP_MAIN_THREAD_ATTR populate the .sceModuleInfo
 *     section the PSP loader reads from EBOOT.PBP.
 *   - SetupCallbacks() spawns a small thread that registers an exit callback
 *     so the user can press Home → Yes to return to the XMB cleanly.
 *   - GameMain() (defined inside Engine.cpp) does the actual engine boot,
 *     update loop, shutdown. We just call it.
 *
 * The engine's `int main` is gated out when POLYPHASE_PLATFORM_ADDON is
 * defined (small arm in Engine.cpp), so our main below is the sole entry.
 *
 * Oct* hooks below are stubs — the BuildTarget-DevEnv project doesn't have
 * its own Main.cpp to provide them, so we supply minimal versions here.
 * Real game projects targeting PSP can override by defining their own
 * Main_PSP.cpp under Source/ (the addon doesn't need a copy then).
 */

#if defined(POLYPHASE_PLATFORM_ADDON)

#include <pspkernel.h>
#include <pspdebug.h>
#include <pspthreadman.h>
#include <pspctrl.h>
#include <pspiofilemgr.h>

#include <stdio.h>
#include <string.h>

#include "Engine.h"
#include "EmbeddedFile.h"
#include "Log.h"

// Embedded-scripts table generated by the editor's packager into
// Generated/EmbeddedScripts.cpp at cook time. The PSP runtime has no
// disk-side Scripts/ folder (the cooker doesn't copy it for embedded
// builds), so without this wiring Lua-attached components silently never
// run -- Tick / Create / signal handlers are all no-ops on the runtime
// side because ScriptUtils has no source to load from. Wired into the
// EngineConfig below in OctPreInitialize, mirroring Standalone/Source/Main.cpp.
extern uint32_t gNumEmbeddedScripts;
extern EmbeddedFile gEmbeddedScripts[];

// Boot-checkpoint log appender. Independent of the engine's SYS_Log so it
// works BEFORE Initialize() runs — if the engine crashes early during init,
// the last checkpoint written tells us exactly where. Writes to the same
// file SYS_Log uses so everything ends up in one place.
//
// Path: ms0:/PSP/GAME/POLYPHASE/polyphase.log
//   On PPSSPP that's <user>/Documents/PPSSPP/memstick/PSP/GAME/POLYPHASE/polyphase.log
//   On real PSP hardware that's a real path on the memory stick.
// PPSSPP launches the EBOOT.PBP directly from the project's Packaged/ dir
// without ever installing to ms0:/PSP/GAME/, so the parent directory tree
// doesn't exist on first boot. sceIoMkdir is single-level only — chain it.
// EEXIST returns < 0 but is harmless; the open below works either way.
static void Psp_EnsureBootLogDir()
{
    sceIoMkdir("ms0:/PSP", 0777);
    sceIoMkdir("ms0:/PSP/GAME", 0777);
    sceIoMkdir("ms0:/PSP/GAME/POLYPHASE", 0777);
}

static void Psp_BootLog(const char* msg)
{
    if (msg == nullptr) return;
    fputs(msg, stdout); fputc('\n', stdout); fflush(stdout);
    Psp_EnsureBootLogDir();
    const SceUID fd = sceIoOpen("ms0:/PSP/GAME/POLYPHASE/polyphase.log",
                                PSP_O_WRONLY | PSP_O_CREAT | PSP_O_APPEND, 0777);
    if (fd < 0) return;
    sceIoWrite(fd, msg, strlen(msg));
    sceIoWrite(fd, "\n", 1);
    sceIoClose(fd);
}

static void Psp_TruncateBootLog()
{
    // Open with TRUNC to clear any prior session's contents — keeps the log
    // bounded and means each run starts fresh.
    Psp_EnsureBootLogDir();
    const SceUID fd = sceIoOpen("ms0:/PSP/GAME/POLYPHASE/polyphase.log",
                                PSP_O_WRONLY | PSP_O_CREAT | PSP_O_TRUNC, 0777);
    if (fd >= 0)
    {
        const char* hdr = "=== Polyphase PSP boot log ===\n";
        sceIoWrite(fd, hdr, strlen(hdr));
        sceIoClose(fd);
    }
}

PSP_MODULE_INFO("Polyphase", 0, 1, 0);
PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER);
// Stack size for the PSP main thread. 256 KB matches what most homebrew
// engines pick — Polyphase's reflection + scene-graph tables push past the
// default 16 KB.
PSP_MAIN_THREAD_STACK_SIZE_KB(256);

// -------------------------------------------------------------------------
// Oct* hooks — minimal stubs. Engine/Source/Engine/OctHookAutoRegister.cpp
// resolves these externs at static-init time and forwards them through
// RegisterOctHooks(), so the engine sees them as the game's hooks.
// -------------------------------------------------------------------------

void OctPreInitialize(EngineConfig& config)
{
    GetEngineState()->mStandalone = true;

    // Force PSP screen dimensions in the EngineConfig. This is what most code
    // checks; the equally-important EngineState copy is forced again in
    // OctPostInitialize below (see comment there for why both are needed).
    config.mWindowWidth  = 480;
    config.mWindowHeight = 272;

    config.mEmbeddedScriptCount = gNumEmbeddedScripts;
    config.mEmbeddedScripts     = gEmbeddedScripts;
}

void OctPostInitialize()
{
    // OctPreInitialize sets EngineConfig values BEFORE GameMain's
    // ReadEngineConfig() loads Config.ini, which overwrites our 480x272 with
    // whatever the project authored for desktop (typically 1280x720). Then
    // Initialize() copies the clobbered values into EngineState.
    // Renderer::GetViewportWidth/Height reads from EngineState live every
    // frame, so widgets compute their rects against the wrong (desktop)
    // viewport and FullStretch quads come out as 1280x720, which PSP's
    // 480x272 scissor crops to a tiny corner -- making a fullscreen Quad
    // texture look enormously zoomed in.
    //
    // Override here in OctPostInitialize so we land AFTER ReadEngineConfig
    // and AFTER Initialize's config-to-state copy. PSP's GFX_Initialize
    // hardcodes its framebuffer size to 480x272 already, so changing the
    // logical size at this point only fixes widget sizing -- no resource
    // re-creation needed.
    const uint32_t beforeW = GetEngineState()->mWindowWidth;
    const uint32_t beforeH = GetEngineState()->mWindowHeight;
    GetEngineState()->mWindowWidth  = 480;
    GetEngineState()->mWindowHeight = 272;
    LogDebug("[PSP] OctPostInitialize: window %ux%u -> 480x272", beforeW, beforeH);
}
void OctPreUpdate() {}
void OctPostUpdate() {}
void OctPreShutdown() {}
void OctPostShutdown() {}

// -------------------------------------------------------------------------
// PSP exit-callback wiring. Without this, the Home button doesn't cleanly
// return to the XMB — the game just freezes.
// -------------------------------------------------------------------------

static int ExitCallback(int /*arg1*/, int /*arg2*/, void* /*common*/)
{
    sceKernelExitGame();
    return 0;
}

static int CallbackThread(SceSize /*args*/, void* /*argp*/)
{
    const int cb = sceKernelCreateCallback("exit_cb", &ExitCallback, nullptr);
    sceKernelRegisterExitCallback(cb);
    sceKernelSleepThreadCB();
    return 0;
}

static int SetupCallbacks()
{
    const int th = sceKernelCreateThread("update_thread", &CallbackThread,
                                         0x11, 0xFA0, 0, nullptr);
    if (th >= 0) sceKernelStartThread(th, 0, nullptr);
    return th;
}

// -------------------------------------------------------------------------
// Engine entry. GameMain is defined inside Engine/Source/Engine/Engine.cpp
// and bundles ReadCommandLineArgs → OctPreInitialize → Initialize →
// OctPostInitialize → loop(Update) → Shutdown. We just call it; the
// callbacks above keep Home-button exit working.
// -------------------------------------------------------------------------

extern void GameMain(int32_t argc, char** argv);

int main(int argc, char** argv)
{
    // Wipe last session's log first, then start writing checkpoints. If the
    // engine crashes early we can read the file from the host afterwards and
    // see exactly how far we got before the lights went out.
    Psp_TruncateBootLog();
    Psp_BootLog("[1] main() entered");

    SetupCallbacks();
    Psp_BootLog("[2] SetupCallbacks() returned");

    Psp_BootLog("[3] About to call GameMain()");
    GameMain(argc, argv);
    Psp_BootLog("[4] GameMain() returned cleanly");

    sceKernelExitGame();
    return 0;
}

#endif // POLYPHASE_PLATFORM_ADDON
